# Generated by Django 4.2.17 on 2024-12-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
